[package]
name = "tantivy"
version = "0.12.0-rc.2"
readme = "README.md"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license-file = "LICENSE"
license = "MIT"

[lib]
name = "tantivy"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.11"
tantivy = "0.12.0"
itertools = "0.9.0"
futures = "0.3.4"

[dependencies.pyo3]
version = "0.9.2"
features = ["extension-module"]

[package.metadata.maturin]
requires-python = ">=3.7"
project-url = ["https://github.com/tantivy-search/tantivy-py"]
