[package]
name = "tantivy"
version = "0.14.0"
readme = "README.md"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "MIT"

[lib]
name = "tantivy"
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.19"
tantivy = "0.14"
itertools = "0.9.0"
futures = "0.3.5"
ahash = "0.7.4"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[package.metadata.maturin]
requires-python = ">=3.7"
project-url =  { Source = "https://github.com/quickwit-inc/tantivy-py" }
